# Generated by Django 4.1.5 on 2023-01-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('sodio', models.FloatField(null=True, verbose_name='sodio')),
                ('calcio', models.FloatField(null=True, verbose_name='calcio')),
                ('magnesio', models.FloatField(null=True, verbose_name='magnesio')),
                ('sulfato', models.FloatField(null=True, verbose_name='sulfato')),
                ('cloruro', models.FloatField(null=True, verbose_name='cloruro')),
                ('nitrato', models.FloatField(null=True, verbose_name='nitrato')),
                ('potasio', models.FloatField(null=True, verbose_name='potasio')),
                ('pH', models.FloatField(null=True, verbose_name='pH')),
                ('conductividadAgua', models.FloatField(null=True, verbose_name='conductividad')),
                ('solidosTotalesDisueltos', models.FloatField(null=True, verbose_name='solidosTotales')),
                ('temperatura', models.FloatField(null=True, verbose_name='temperatura')),
                ('ras', models.FloatField(null=True, verbose_name='ras')),
                ('alcalinidad', models.FloatField(null=True, verbose_name='alcalinidad')),
                ('durezaTotal', models.FloatField(null=True, verbose_name='durezaTotal')),
            ],
        ),
        migrations.CreateModel(
            name='Alcalinidad',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('concentracionAcidoSulfurico', models.FloatField(null=True, verbose_name='concentracionAcidoSulfurico')),
                ('volumenFenolftaleina', models.FloatField(null=True, verbose_name='volumenFenolftaleina')),
                ('volumenNaranjaDeMetilo', models.FloatField(null=True, verbose_name='volumenNaranjaDeMetilo')),
                ('alcalinidadDeNaranjaDeMetilo', models.FloatField(null=True, verbose_name='alcalinidadDeNaranjaDeMetilo')),
                ('alcalinidadFenolftaleina', models.FloatField(null=True, verbose_name='alcalinidadFenolftaleina')),
                ('bicarbonato', models.FloatField(null=True, verbose_name='bicarbonato')),
                ('carbonato', models.FloatField(null=True, verbose_name='carbonato')),
                ('oxidrilo', models.FloatField(null=True, verbose_name='oxidrilo')),
                ('alcalinidadTotal', models.FloatField(null=True, verbose_name='alcalinidadTotal')),
            ],
        ),
        migrations.CreateModel(
            name='Dureza',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('durezaTotal', models.FloatField(null=True, verbose_name='durezaTotal')),
                ('calcio', models.FloatField(null=True, verbose_name='calcio')),
                ('magnesio', models.FloatField(null=True, verbose_name='magnesio')),
                ('bicarbonato', models.FloatField(null=True, verbose_name='bicarbonato')),
                ('carbonato', models.FloatField(null=True, verbose_name='carbonato')),
                ('oxidrilo', models.FloatField(null=True, verbose_name='oxidrilo')),
                ('durezaCarbonacea', models.FloatField(null=True, verbose_name='durezaCarbonacea')),
                ('durezaNoCarbonacea', models.FloatField(null=True, verbose_name='durezaNoCarbonacea')),
                ('durezaPorCalcio', models.FloatField(null=True, verbose_name='durezaPorCalcio')),
                ('alcalinidadTotal', models.FloatField(null=True, verbose_name='alcalinidadTotal')),
            ],
        ),
        migrations.CreateModel(
            name='Sar',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='nombre')),
                ('sodio', models.FloatField(null=True, verbose_name='sodio')),
                ('calcio', models.FloatField(null=True, verbose_name='calcio')),
                ('magnesio', models.FloatField(null=True, verbose_name='magnesio')),
                ('conductividadAgua', models.FloatField(null=True, verbose_name='conductividad')),
                ('solidosTotalesDisueltos', models.FloatField(null=True, verbose_name='solidosTotales')),
            ],
        ),
    ]
