# Generated by Django 4.1.5 on 2023-01-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sar',
            name='conductividadAgua',
        ),
        migrations.RemoveField(
            model_name='sar',
            name='solidosTotalesDisueltos',
        ),
        migrations.AddField(
            model_name='agua',
            name='bicarbonato',
            field=models.FloatField(null=True, verbose_name='bicarbonato'),
        ),
        migrations.AddField(
            model_name='agua',
            name='carbonato',
            field=models.FloatField(null=True, verbose_name='carbonato'),
        ),
        migrations.AddField(
            model_name='sar',
            name='bicarbonato',
            field=models.FloatField(null=True, verbose_name='bicarbonato'),
        ),
        migrations.AddField(
            model_name='sar',
            name='relacionSar',
            field=models.FloatField(null=True, verbose_name='relacionSar'),
        ),
        migrations.AddField(
            model_name='sar',
            name='salinidadCe',
            field=models.FloatField(null=True, verbose_name='salinidadCe'),
        ),
    ]
