# Generated by Django 4.1.5 on 2023-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0002_remove_sar_conductividadagua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sar',
            name='sarNormal',
            field=models.FloatField(null=True, verbose_name='sarNormal'),
        ),
    ]
