# Generated by Django 4.1.5 on 2023-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0003_sar_sarnormal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sar',
            name='riesgo',
            field=models.IntegerField(null=True, verbose_name='riesgo'),
        ),
    ]
