# Generated by Django 4.1.5 on 2023-01-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0004_sar_riesgo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcalinidad',
            name='bicarbonato',
        ),
        migrations.RemoveField(
            model_name='alcalinidad',
            name='carbonato',
        ),
        migrations.RemoveField(
            model_name='alcalinidad',
            name='oxidrilo',
        ),
        migrations.AddField(
            model_name='alcalinidad',
            name='alcalinidadCo3',
            field=models.FloatField(null=True, verbose_name='alcalinidadCo3'),
        ),
        migrations.AddField(
            model_name='alcalinidad',
            name='alcalinidadHco3',
            field=models.FloatField(null=True, verbose_name='alcalinidadHco3'),
        ),
        migrations.AddField(
            model_name='alcalinidad',
            name='alcalinidadOh',
            field=models.FloatField(null=True, verbose_name='alcalinidadOh'),
        ),
        migrations.AddField(
            model_name='alcalinidad',
            name='volumenMuestra',
            field=models.FloatField(null=True, verbose_name='volumenMuestra'),
        ),
    ]
