# Generated by Django 4.1.5 on 2023-01-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0005_remove_alcalinidad_bicarbonato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dureza',
            name='durezaPorCalcio',
        ),
        migrations.RemoveField(
            model_name='dureza',
            name='oxidrilo',
        ),
    ]
