# Generated by Django 4.1.5 on 2023-01-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0006_remove_dureza_durezaporcalcio_remove_dureza_oxidrilo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agua',
            name='alcalinidad',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='calcio',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='carbonato',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='durezaTotal',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='magnesio',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='nitrato',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='pH',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='potasio',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='sulfato',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='agua',
            name='boro',
            field=models.FloatField(null=True, verbose_name='boro'),
        ),
        migrations.AddField(
            model_name='agua',
            name='hierro',
            field=models.FloatField(null=True, verbose_name='hierro'),
        ),
        migrations.AddField(
            model_name='agua',
            name='manganeso',
            field=models.FloatField(null=True, verbose_name='manganeso'),
        ),
        migrations.AddField(
            model_name='agua',
            name='sulfuroDeHidrogeno',
            field=models.FloatField(null=True, verbose_name='sulfuroDeHidrogeno'),
        ),
        migrations.AlterField(
            model_name='agua',
            name='conductividadAgua',
            field=models.FloatField(null=True, verbose_name='conductividadAgua'),
        ),
        migrations.AlterField(
            model_name='agua',
            name='solidosTotalesDisueltos',
            field=models.FloatField(null=True, verbose_name='solidosTotalesDisueltos'),
        ),
    ]
